---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: gitea
  namespace: gitea-stage
  labels:
    app: gitea-stage
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "latest-rootless"
      from:
        kind: DockerImage
        name: docker.io/gitea/gitea:latest-rootless
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Local
