---
# anyuid required for init container to chown NFS-mounted /data volume
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-stage-anyuid
  namespace: gitea-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: gitea-stage
  namespace: gitea-stage
