APP_NAME = Gitea: Git with a cup of tea
RUN_MODE = prod
RUN_USER = git
WORK_PATH = /data/gitea

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH = /data/gitea
DOMAIN = gitea.home.mburnsfire.net
SSH_DOMAIN = rpi5.home.mburnsfire.net
HTTP_PORT = 3000
ROOT_URL = https://gitea.home.mburnsfire.net/
DISABLE_SSH = false
SSH_PORT = 2222
SSH_LISTEN_PORT = 2222
LFS_START_SERVER = true
LFS_JWT_SECRET = Wf9tZ4QiA4DLY5SKk_-pZ07J87Io-e5oK9NXXVKShhY
OFFLINE_MODE = false

[database]
PATH = /data/gitea/gitea.db
DB_TYPE = postgres
HOST = gitea-db:5432
NAME = gitea
USER = giteauser
PASSWD = giteapass
LOG_SQL = false
SCHEMA = 
SSL_MODE = disable

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER = file

[picture]
AVATAR_UPLOAD_PATH = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars

[attachment]
PATH = /data/gitea/attachments

[log]
MODE = console
LEVEL = info
ROOT_PATH = /data/gitea/log

[security]
INSTALL_LOCK = true
SECRET_KEY = 
REVERSE_PROXY_LIMIT = 1
REVERSE_PROXY_TRUSTED_PROXIES = *
INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3NTY0MDkyMjl9.2qdcvPOwSfeitWSMcnB-5CVfgtZxeVlRTJYanpOojWA
PASSWORD_HASH_ALGO = pbkdf2

[service]
DISABLE_REGISTRATION = false
REQUIRE_SIGNIN_VIEW = false
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = true
ALLOW_ONLY_EXTERNAL_REGISTRATION = false
ENABLE_CAPTCHA = false
DEFAULT_KEEP_EMAIL_PRIVATE = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING = true
NO_REPLY_ADDRESS = noreply.gitea.yourname.synology.me

[lfs]
PATH = /data/git/lfs

[mailer]
ENABLED = true
#SMTP_ADDR = smtp.gmail.com
#SMTP_PORT = 587
SMTP_ADDR = shift.home.mburnsfire.net
SMTP_PORT = 25
PROTOCOL = smtp
FROM = "Gitea" <mburns72h+gitea@gmail.com>
#USER = mburns72h@gmail.com
#PASSWD = dxlv giht nmen alih

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[cron.update_checker]
ENABLED = true

[repository.pull-request]
DEFAULT_MERGE_STYLE = merge

[repository.signing]
DEFAULT_TRUST_MODEL = committer

[oauth2]
JWT_SECRET = BzXGOoL0LlkeJB4knRRBzZCR2fmwjkDihHL6ST7o2hU

[migrations]
ALLOWED_DOMAINS = *.home.mburnsfire.net
ALLOW_LOCALNETWORKS = true
