#!/bin/bash
# Generate and apply secrets for Gitea staging deployment (non-HA PostgreSQL)
set -e

echo "Generating secrets for gitea-staging..."

# Generate passwords and tokens
REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d '/')
INTERNAL_TOKEN=$(openssl rand -base64 105 | tr -d '\n/')
SECRET_KEY=$(openssl rand -base64 32 | tr -d '/')
LFS_JWT_SECRET=$(openssl rand -base64 32 | tr -d '/')
OAUTH2_JWT_SECRET=$(openssl rand -base64 32 | tr -d '/')

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Copy template to secrets.yaml if it doesn't exist
if [ ! -f "${SCRIPT_DIR}/secrets.yaml" ]; then
    echo "Creating secrets.yaml from template..."
    cp "${SCRIPT_DIR}/secrets-simple.yaml.example" "${SCRIPT_DIR}/secrets.yaml"
fi

# Update secrets.yaml
sed -i.bak \
    -e "s|CHANGE_ME_redis_password|${REDIS_PASSWORD}|g" \
    -e "s|CHANGE_ME_generate_with_gitea_generate_secret_INTERNAL_TOKEN|${INTERNAL_TOKEN}|g" \
    -e "s|CHANGE_ME_generate_with_gitea_generate_secret_SECRET_KEY|${SECRET_KEY}|g" \
    "${SCRIPT_DIR}/secrets.yaml"

# Replace all occurrences of CHANGE_ME_generate_with_gitea_generate_secret_JWT_SECRET
# First with LFS_JWT_SECRET, second with OAUTH2_JWT_SECRET
awk -v lfs="${LFS_JWT_SECRET}" -v oauth="${OAUTH2_JWT_SECRET}" '
BEGIN { count=0 }
/CHANGE_ME_generate_with_gitea_generate_secret_JWT_SECRET/ {
    count++
    if (count == 1) {
        sub(/CHANGE_ME_generate_with_gitea_generate_secret_JWT_SECRET/, lfs)
    } else if (count == 2) {
        sub(/CHANGE_ME_generate_with_gitea_generate_secret_JWT_SECRET/, oauth)
    }
}
{ print }
' "${SCRIPT_DIR}/secrets.yaml" > "${SCRIPT_DIR}/secrets.yaml.tmp"
mv "${SCRIPT_DIR}/secrets.yaml.tmp" "${SCRIPT_DIR}/secrets.yaml"

echo "Secrets generated and updated in secrets.yaml"
echo ""
echo "Note: PostgreSQL password will be auto-generated by Helm chart"
echo "      and stored in secret: gitea-staging-postgresql"
echo ""
echo "Applying secrets to gitea-staging namespace..."

oc apply -f "${SCRIPT_DIR}/secrets.yaml"

echo "Done! Secrets applied to gitea-staging namespace."
echo ""
echo "To retrieve the auto-generated PostgreSQL password later:"
echo "  oc get secret gitea-staging-postgresql -n gitea-staging -o jsonpath='{.data.password}' | base64 -d"
