---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-staging
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: argocd-application
    app.kubernetes.io/part-of: gitea
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitea-staging

  sources:
    - repoURL: https://dl.gitea.com/charts/
      chart: gitea
      targetRevision: 12.5.3
      helm:
        releaseName: gitea-staging
        valueFiles:
          - $values/staging/values.yaml

    - repoURL: https://gitea.home.mburnsfire.net/homelab/gitea-k8s.git
      targetRevision: main
      ref: values

    - repoURL: https://gitea.home.mburnsfire.net/homelab/gitea-k8s.git
      targetRevision: main
      path: staging
      directory:
        include: "{imagestream.yaml,rbac.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: gitea-staging-init
      jqPathExpressions:
        - '.data["config_environment.sh"]'
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      name: gitea-staging
      namespace: gitea-staging
      jsonPointers:
        - /data/config_environment.sh
