---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitea-prod
  namespace: openshift-gitops
spec:
  description: Gitea production - restricted to gitea namespace only

  sourceRepos:
    - https://dl.gitea.com/charts/
    - https://gitea.home.mburnsfire.net/homelab/gitea-k8s.git

  destinations:
    - namespace: gitea
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
