---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: redis
  namespace: gitea
  labels:
    app: gitea
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 7.2.5-debian-12-r4
      from:
        kind: DockerImage
        name: docker.io/bitnami/redis:7.2.5-debian-12-r4
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Local
